NIXPACKS_PYTHON_VERSION="3.11"
providers = ["...", "python"]

[phases.install]
cmds =["echo install phase","pip install -r app/requirements.txt"]


[start]
cmd = "python -m uvicorn app.main:app --reload"

