[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
providers = ["...", "python"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds =["echo install phase","pip install -r app/requirements.txt"]


[start]
cmd = "python -m uvicorn app.main:app --reload"

